### ISSUE TITLE
Trait class must have a no-arguments constructor

### ISSUE THREAD

**Issue by MarkehMe** [CitizensDev/CitizensAPI#17]
* Citizens v2.0.19-SNAPSHOT (build 1379)
* git-Paper-785 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
* Java 1.8.0_25

---

When I register my trait, I get thrown with this error - even though there is a no-arguments construct:

```
java.lang.IllegalArgumentException: Trait class must have a no-arguments constructor
	at net.citizensnpcs.api.trait.TraitInfo.create(TraitInfo.java:81) ~[?:?]
	at my.test.trait.MyTrait.register(MyTrait.java:21) ~[?:?]
	at my.test.Plugin.onEnable(Plugin.java:40) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.jar:git-Paper-785]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.jar:git-Paper-785]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.jar:git-Paper-785]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.jar:git-Paper-785]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.jar:git-Paper-785]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.jar:git-Paper-785]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.jar:git-Paper-785]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.jar:git-Paper-785]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.jar:git-Paper-785]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.jar:git-Paper-785]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

```

```java
@TraitName("traittest") 
public class MyTrait extends Trait {

	// ----------------------------------------
	// STATIC
	// ----------------------------------------
	
	private static TraitInfo traitInfo;
	public static void register() {
		traitInfo = TraitInfo.create(MyTrait.class);
		
		CitizensAPI.getTraitFactory().registerTrait(traitInfo);
	}
	
	public static void deregister() {
		CitizensAPI.getTraitFactory().deregisterTrait(traitInfo);
		
		traitInfo = null;
	}
	
	// ----------------------------------------
	// CONSTRUCT
	// ----------------------------------------
	
	protected MyTrait() {
		super("traittest");
	}

// ...

```

Which is weird.. I followed just as [the wiki](http://wiki.citizensnpcs.co/API#Creating_a_Trait) said. I assume this is a bug?

**Comment by mcmonkey4eva** [comment]
The wiki page you linked has a `public` constructor, you have a `protected` one.

**Comment by MarkehMe** [comment]
Ah.. eclipse auto filled in a construct for me. Oddly, it picked ```protected```.. my mistake. 

Thanks for the fast response 👍
