### ISSUE TITLE
Getting NPC from id throws nullpointerexemption

### ISSUE THREAD

**Issue by XglockManLP** [CitizensDev/CitizensAPI#69]
I tried to get NPC from id CitizensAPI.getNPCRegistry().getById(_npcid) but it always throws nullpointerexemption.

[23:00:17 ERROR]: Error occurred while enabling XGCoreHub vb0.0.1 (Is it up to date?)
java.lang.NullPointerException: null
at cz.xglockman.XGCore.Nametag.Nametag.hideNPCnt(Nametag.java:161) ~[?:?]
at cz.xglockman.XGCore.NPC.NPC.load(NPC.java:31) ~[?:?]
at cz.xglockman.XGCore.NPC.NPCAPI.createnpc(NPCAPI.java:64) ~[?:?]
at cz.xglockman.XGCore.NPC.NPCAPI.loadnpcs(NPCAPI.java:24) ~[?:?]
at cz.xglockman.XGCoreHub.Loader.onEnable(Loader.java:55) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Paper-33d42c8e]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[server.jar:git-Paper-33d42c8e]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[server.jar:git-Paper-33d42c8e]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[server.jar:git-Paper-33d42c8e]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[server.jar:git-Paper-33d42c8e]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[server.jar:git-Paper-33d42c8e]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[server.jar:git-Paper-33d42c8e]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[server.jar:git-Paper-33d42c8e]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[server.jar:git-Paper-33d42c8e]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[server.jar:git-Paper-33d42c8e]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by mcmonkey4eva** [comment]
That stacktrace is information for *you*, not for us. We can provide help with Citizens usage, but we can't teach how to work with Java - there's support with basic Java usage elsewhere.

You should probably review the setup information for Citizens API usage @ https://wiki.citizensnpcs.co/API

If you narrow down the basic Java usage parts and get stuck on the Citizens part, feel free to ask for help on our Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel, but please make sure to post full background information on what you're doing, with full `logs/latest.log`, your full `pom.xml`, your full java source code, etc.
