### ISSUE TITLE
Unable to create or access NPC

### ISSUE THREAD

**Issue by KadTheAad** [CitizensDev/CitizensAPI#72]
### Server Logs + Error:
```
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.2+7) Host: Mac OS X 12.0.1 (aarch64)
Loading libraries, please wait...
[09:48:00 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:48:00 INFO]: Reloading ResourceManager: Default, bukkit
[09:48:01 INFO]: Loaded 7 recipes
[09:48:01 INFO]: Starting minecraft server version 1.16.5
[09:48:01 INFO]: Loading properties
[09:48:01 INFO]: This server is running Paper version git-Paper-792 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[09:48:01 INFO]: Debug logging is disabled
[09:48:01 INFO]: Server Ping Player Sample Count: 12
[09:48:01 INFO]: Using 4 threads for Netty based IO
[09:48:01 INFO]: Default game type: SURVIVAL
[09:48:01 INFO]: Generating keypair
[09:48:01 INFO]: Starting Minecraft server on *:25565
[09:48:01 INFO]: Using default channel type
[09:48:02 INFO]: [Citizens] Loading Citizens v2.0.29-SNAPSHOT (build 2419)
[09:48:02 INFO]: [Sentinel] Loading Sentinel v2.4.0-SNAPSHOT (build 446)
[09:48:02 INFO]: [CombatNPCs] Loading CombatNPCs v1.0-SNAPSHOT
[09:48:02 INFO]: Server permissions file permissions.yml is empty, ignoring it
[09:48:02 INFO]: Preparing level "world"
[09:48:02 INFO]: Preparing start region for dimension minecraft:overworld
[09:48:02 INFO]: Preparing spawn area: 0%
[09:48:02 INFO]: Time elapsed: 248 ms
[09:48:02 INFO]: Preparing start region for dimension minecraft:the_nether
[09:48:02 INFO]: Preparing spawn area: 0%
[09:48:02 INFO]: Preparing spawn area: 11%
[09:48:03 INFO]: Time elapsed: 529 ms
[09:48:03 INFO]: Preparing start region for dimension minecraft:the_end
[09:48:03 INFO]: Preparing spawn area: 0%
[09:48:03 INFO]: Time elapsed: 213 ms
[09:48:03 INFO]: [Citizens] Enabling Citizens v2.0.29-SNAPSHOT (build 2419)
[09:48:03 INFO]: [Citizens] Vault not found -> no economy handling.
[09:48:03 INFO]: [Sentinel] Enabling Sentinel v2.4.0-SNAPSHOT (build 446)
[09:48:03 INFO]: [Sentinel] Sentinel loading...
[09:48:03 INFO]: [Sentinel] Running on java version: 16.0.2
[09:48:03 INFO]: [Sentinel] Sentinel loaded on a fully supported Minecraft version. If you encounter any issues or need to ask a question, please join our Discord at https://discord.gg/Q6pZGSR and post in the '#sentinel' channel.
[09:48:03 INFO]: [Sentinel] Sentinel loaded!
[09:48:03 INFO]: [CombatNPCs] Enabling CombatNPCs v1.0-SNAPSHOT
[09:48:03 INFO]: Running delayed init tasks
[09:48:03 INFO]: [Citizens] Loaded 1 NPCs.
[09:48:03 INFO]: Done (1.974s)! For help, type "help"
[09:48:03 INFO]: Timings Reset
[09:48:11 INFO]: UUID of player DiamondLuda is 6ab49aec-d093-4eec-8812-89f95f6b0bf5
[09:48:11 INFO]: DiamondLuda joined the game
[09:48:11 INFO]: DiamondLuda[/127.0.0.1:52674] logged in with entity id 213 at ([world]230.90351538076416, 69.0, 25.397396154719843)
[09:48:14 INFO]: DiamondLuda issued server command: /createcombatnpc
[09:48:14 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'createcombatnpc' in plugin CombatNPCs v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1400) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-792]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: no implementation set
	at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:79) ~[?:?]
	at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:111) ~[?:?]
	at com.kadtheaad.combatnpcs.commands.MainCommand.onCommand(MainCommand.java:22) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-792]
	... 19 more
```
### Code:
```
public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        Player player = (Player) sender;
        NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.PLAYER, "Welcome");
        npc.spawn(player.getLocation());
        return true;
    }
```

**Comment by mcmonkey4eva** [comment]
Most likely just linked the API incorrectly in maven - refer to https://wiki.citizensnpcs.co/API

If you get lost consider also asking for help on Discord @ https://discord.gg/Q6pZGSR
