### ISSUE TITLE
mising plugin.yml in citizens api

### ISSUE THREAD

**Issue by ArendelYT** [CitizensDev/CitizensAPI#79]
in my console when loading citizens api it say it missing plugin.yml file.I tried reinstal it like 3 times but same error. There's that error: [ERROR] Could not load 'plugins/citizensapi-2.0.32-SNAPSHOT.jar' in folder 'plugins'

org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:435) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]

at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]

at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]

at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]

at java.lang.Thread.run(Thread.java:1589) ~[?:?]

Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

... 7 more and here is that api:
[citizensapi-2.0.32-SNAPSHOT.zip](https://github.com/CitizensDev/CitizensAPI/files/12550425/citizensapi-2.0.32-SNAPSHOT.zip)

**Comment by mcmonkey4eva** [comment]
CitizensAPI is not a plugin, it's an internal API, you should not be using it. Download Citizens from https://ci.citizensnpcs.co/job/Citizens2/ or spigot
